<a href="https://colab.research.google.com/github/sh1vam31/Complete_DataScience/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**

## 1 What is Pandas and Why Use It?
Pandas is a powerful Python library for data analysis and manipulation.

Key points:

Provides two main data structures: Series (1D) and DataFrame (2D).
Makes working with tabular data easy and fast.
Ideal for cleaning, transforming, and analyzing datasets.
Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

### Import the pandas

In [2]:
import numpy as np
import pandas as pd

## 2 Understanding Series & DataFrame



*   Series: One-dimensional labeled array, like a column in Excel.
*   DataFrame: Two-dimensional table, similar to an Excel sheet or SQL table.

## Creating a Series from Python Lists or Dictionaries

In [9]:
a = [12, 34, 45, 74, 66]
s = pd.Series(a, name = "Marks")
s

d = {"vashu": 99, "shivam": 88,}
s2 = pd.Series(d, name = "marks")
s2

vashu     99
shivam    88
Name: marks, dtype: int64

## Creating a DataFrame

In [10]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [90, 85, 78, 92],
    "Subject": ["Math", "Science", "History", "English"]
}

pd.DataFrame(a)

      Name  Marks  Subject
0    Alice     90     Math
1      Bob     85  Science
2  Charlie     78  History
3    David     92  English

## Creating DataFrame from NumPy Arrays

In [15]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

df = pd.DataFrame(a, columns = ["A", "B", "C"])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

## 1 Inspecting Data
Quick ways to understand your dataset:

- head(n) → first n rows (default 5)
- tail(n) → last n rows
- info() → columns, non-null counts, and dtypes
- shape → (rows, columns)
- dtypes → data type of each column

In [9]:
import pandas as pd

a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
b
print()
print(b.head())
print()
print(b.head(3))
print()
print(b.tail())
print()
print(b.tail(2))
print()
print(b.shape)
print()
print(b.info())
print()
print(b.dtypes)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

    Name  Age  Score
3  David   40     85
4   Emma   22     95

(5, 3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None

Name     object
Age       int64
Score     int64
dtype: object

## 2 Selecting Columns & Rows
Ways to access parts of a DataFrame:

- Single column → `df['col']`
- Multiple columns → `df[['col1','col2']]`
- Label-based selection → `df.loc[row_label, col_label]`
- Integer-index selection → `df.iloc[row_idx, col_idx]` Tip: : means "all rows/columns" in that dimension.

In [26]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
print(b)
print()
print(b["Name"])
print()
print(b[["Name", "Age"]])     # whenever we use the fancy indexing we have to use the 2 square brackats
print()
print(b.loc[1])
print()
print(b.loc[[2, 3]])
print()
print(b.loc[4,"Score"])
print()
print(b.loc[1:4, ["Name", "Age"]])
print()
print(b.iloc[2, 2])

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

0      Alice
1        Bob
2    Charlie
3      David
4       Emma
Name: Name, dtype: object

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   22

Name     Bob
Age       30
Score     92
Name: 1, dtype: object

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

95

      Name  Age
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   22

79

## 3 Index & Columns Overview
- `df.index` → row labels
- `df.columns` → column names
- `df.values` → underlying NumPy array

In [32]:
print(b)
print()
print(b.index)
print()
print(b.columns)
print()
print(b.values)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

RangeIndex(start=0, stop=5, step=1)

Index(['Name', 'Age', 'Score'], dtype='object')

[['Alice' 25 88]
 ['Bob' 30 92]
 ['Charlie' 35 79]
 ['David' 40 85]
 ['Emma' 22 95]]

## 4 Renaming Columns & Setting an Index
- Rename columns → `df.rename(columns={'old':'new'}, inplace=False)`
- Set a column as `index → df.set_index('column_name', inplace=False)`
- Reset index → `df.reset_index(inplace=False)` If you don't use `inplace=True`, remember to assign the result back to a variable.

In [48]:
print(b)
print()
c = b.rename(columns = {"Score": "marks"}, inplace = False)
print(c)
print("\nThe Original dataframe")
print(b)
print()
c = b.set_index("Name")
print(c)
print()
b.reset_index(inplace = False)
print(b)

   index     Name  Age  Score
0      0    Alice   25     88
1      1      Bob   30     92
2      2  Charlie   35     79
3      3    David   40     85
4      4     Emma   22     95

   index     Name  Age  marks
0      0    Alice   25     88
1      1      Bob   30     92
2      2  Charlie   35     79
3      3    David   40     85
4      4     Emma   22     95

The Original dataframe
   index     Name  Age  Score
0      0    Alice   25     88
1      1      Bob   30     92
2      2  Charlie   35     79
3      3    David   40     85
4      4     Emma   22     95

         index  Age  Score
Name
Alice        0   25     88
Bob          1   30     92
Charlie      2   35     79
David        3   40     85
Emma         4   22     95

   index     Name  Age  Score
0      0    Alice   25     88
1      1      Bob   30     92
2      2  Charlie   35     79
3      3    David   40     85
4      4     Emma   22     95

## Mini Practice
- Create a DataFrame with at least 5 rows and 4 columns (mix of numeric + text).
- Show the first 3 rows, last 2 rows, and the info.
- Select a sub-DataFrame with only 2 columns.
- Rename one column and set any column as index, then reset it back.
- Print df.shape, df.dtypes, and df.columns.

In [66]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Chennai"],
    "Score": [85, 91, 78, 88, 95]
}

df = pd.DataFrame(data)
print("\nFirst Three Rows")
print(df.head(3))
print("\nLast Two Rows")
print(df.tail(2))
print("\nInfo")
print(df.info())
print("\n 2 columns")
print(df[["Name", "Age"]])
print("\n Rename")
c = df.rename(columns = {"Score" : "Marks"})
print(c)
print("\n Set Index")
s = df.set_index("Name")
print(s)
print("\n Shape")
print(df.shape)
print("\n Dtypes")
print(df.dtypes)
print("\n Columns")
print(df.columns)

First Three Rows
      Name  Age    City  Score
0    Alice   25   Delhi     85
1      Bob   30  Mumbai     91
2  Charlie   35    Pune     78

Last Two Rows
    Name  Age       City  Score
3  David   40  Bangalore     88
4   Emma   22    Chennai     95

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Score   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None

 2 columns
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   22

 Rename
      Name  Age       City  Marks
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     91
2  Charlie   35       Pune     78
3    David   40  Bangalore     88
4     Emma   22    Chennai     95

 Set Index
         Age       City  Score
Name
Alice     25      Delhi     85
Bob       30     Mumbai     91
Charlie   35       Pune     78
David     40  Bangalore     88
Emma      22    Chennai     95

 Shape
(5, 4)

 Dtypes
Name     object
Age       int64
City     object
Score     int64
dtype: object

 Columns
Index(['Name', 'Age', 'City', 'Score'], dtype='object')

## Handling Missing Values
Real-world datasets often have missing data. Pandas offers:

- isna() / isnull() → detect missing values (returns True/False)
- dropna() → remove missing values (rows/columns)
- fillna() → replace missing values with a given value or method (e.g., forward fill)
- Always inspect how much data is missing before deciding to drop or fill.

In [84]:
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}

df = pd.DataFrame(a)
df.isna()

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False

In [76]:
df.isna().sum()

Name     0
Age      0
City     1
Score    1
dtype: int64

In [71]:
df.dropna()

    Name   Age       City  Score
0  Alice  25.0      Delhi   85.0
3  David  40.0  Bangalore   88.0

In [91]:
print(df)
d = df.copy()
print("\n After filling all the values")
d["Age"] = d["Age"].fillna(d["Age"].mean())
d["City"] = d["City"].fillna(d["City"].mode())
d["Score"] = d["Score"].fillna(d["Score"].mean())
print(d)

d.isna().sum()

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

 After filling all the values
      Name        Age       City  Score
0    Alice  25.000000      Delhi  85.00
1      Bob  33.333333     Mumbai  91.00
2  Charlie  35.000000      Delhi  89.75
3    David  40.000000  Bangalore  88.00
4     Emma  33.333333    Chennai  95.00

Name     0
Age      0
City     0
Score    0
dtype: int64

## Changing Data Types (astype)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.
- Be careful: make sure the data is compatible with the new type!

In [97]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

df = pd.DataFrame(a)
print(df)
print("Change the Score to the float dataType")
df["Score"] = df["Score"].astype(float)
print(df)
print(df.dtypes)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95
Change the Score to the float dataType
Name      object
Age        int64
Score    float64
dtype: object
      Name  Age  Score
0    Alice   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

## Replacing Values `(replace)`
- Use `replace(`) to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [102]:
c = df.copy()
c
c["Name"] = c["Name"].replace("Bob", "Superman")

       Name  Age  Score
0     Alice   25   88.0
1  Superman   30   92.0
2   Charlie   35   79.0
3     David   40   85.0
4      Emma   22   95.0

In [103]:
c["Score"] = c["Score"].replace({88.0:90.0, 79.0:66.0})
c

       Name  Age  Score
0     Alice   25   90.0
1  Superman   30   92.0
2   Charlie   35   66.0
3     David   40   85.0
4      Emma   22   95.0

## Dropping Rows & Columns `(drop)`
- `drop(labels, axis=0)` → drop rows by index labels. axis = 0 means it will search the label in the rows
- `drop(labels, axis=1)` → drop columns by name. axis = 0 means it will search the label in the columns
- Use `inplace=True` if you want to modify the DataFrame directly.

In [112]:
c.drop("Name", axis=1)
c.drop([0,2], axis=0)

       Name  Age  Score
1  Superman   30   92.0
3     David   40   85.0
4      Emma   22   95.0

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset (columns)` and keep` ('first', 'last', or False)`.

In [113]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
    "Age": [25, 30, 35, 25, 30, 40],
    "Score": [88, 92, 79, 88, 92, 85]
}

df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    Alice   25     88
4      Bob   30     92
5    David   40     85

In [120]:
print(df.duplicated())
print()
print(df.duplicated().sum())

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

2

In [115]:
df.drop_duplicates()

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

In [122]:
# 3. Remove duplicates (keep first occurrence)
df_first = df.drop_duplicates()
print("\nAfter dropping duplicates (keep='first'):")
print(df_first)

# 4. Remove duplicates (keep last occurrence)
df_last = df.drop_duplicates(keep="last")
print("\nAfter dropping duplicates (keep='last'):")
print(df_last)

# 5. Remove all duplicates (keep=False)
df_none = df.drop_duplicates(keep=False)
print("\nAfter removing all duplicates (keep=False):")
print(df_none)

# 6. Remove duplicates based on a subset of columns (e.g., Name only)
df_subset = df.drop_duplicates(subset=["Name"])
print("\nAfter dropping duplicates based on 'Name' only:")
print(df_subset)

After dropping duplicates (keep='first'):
      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

After dropping duplicates (keep='last'):
      Name  Age  Score
2  Charlie   35     79
3    Alice   25     88
4      Bob   30     92
5    David   40     85

After removing all duplicates (keep=False):
      Name  Age  Score
2  Charlie   35     79
5    David   40     85

After dropping duplicates based on 'Name' only:
      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

## Mini Practice


1.   Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2.   Clean it step-by-step using what you learned:
- Handle missing values
- Change data types
- Replace incorrect values
- Drop unnecessary rows/columns
- Remove duplicates

In [159]:
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)
print(df)
df.isna().sum()
# Important -> There is a None value in the Age column, and the None is not converted to the int directally so we have to change it to the numeric
df["Age"] = pd.to_numeric(df["Age"])
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Age"] = df["Age"].astype(int)
df["Score"] = df["Score"].fillna(df["Score"].mean())
df["Name"] = df["Name"].fillna("Unknown")
df["City"] = df["City"].replace("Pun", "Pune")

df = df.drop("Extra", axis= 1)
df.duplicated()
df = df.drop_duplicates()
df

     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

      Name  Age       City  Score
0    Alice   25      Delhi   85.0
1      Bob   30     Mumbai   85.4
2   Chrlie   30       Pune   78.0
3    David   40  Bangalore   88.0
5  Unknown   30     Mumbai   91.0

## Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., df['col'] > 50).
- Pass the condition inside df[...] to get matching rows.
- Combine multiple conditions with & (AND), | (OR), and ~ (NOT).
- Parentheses are required when combining conditions.

In [161]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}
df = pd.DataFrame(a)
df

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [163]:
df[df["Age"] > 30]

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

In [167]:
df[(df["Age"] > 25) & (df["Score"] > 85)]

  Name  Age  Score
1  Bob   30     92

In [169]:
df[(df["Age"] > 35) | (df["Score"] > 90)]

    Name  Age  Score
1    Bob   30     92
3  David   40     85
4   Emma   22     95

In [170]:
df[~(df["Score"]> 85)]

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

## Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@ symbol.`

In [172]:
df.query("Age > 30")

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

In [176]:
df.query("Age > 30 and Score > 70")

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

In [178]:
marks = 80
df.query("Score > @marks")

    Name  Age  Score
0  Alice   25     88
1    Bob   30     92
3  David   40     85
4   Emma   22     95

## String Operations on Columns
- Use the `.str `accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [180]:
df

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [181]:
df["Name"].str.contains("a", case = False)

0     True
1    False
2     True
3     True
4     True
Name: Name, dtype: bool

In [189]:
df["Name"] = df["Name"].str.replace("Charlie", "Superman")

       Name  Age  Score
0     Alice   25     88
1       Bob   30     92
2  Superman   35     79
3     David   40     85
4      Emma   22     95

In [192]:
df["Name"].str.startswith("A")

0     True
1    False
2    False
3    False
4    False
Name: Name, dtype: bool

In [193]:
df["Name"].str.endswith("A")

0    False
1    False
2    False
3    False
4    False
Name: Name, dtype: bool

In [194]:
df["Name"].str.upper()

0       ALICE
1         BOB
2    SUPERMAN
3       DAVID
4        EMMA
Name: Name, dtype: object

In [195]:
df["Name"].str.lower()

0       alice
1         bob
2    superman
3       david
4        emma
Name: Name, dtype: object

## Mini Practice
- Build a DataFrame with columns such as Name, Age, City, Score.
- Use boolean indexing to select rows where Age > 25.
- Filter rows where City is either 'Delhi' or 'Mumbai'.
- Use query() to find rows with Score >= 85 and Age < 35.
- Clean a text column using str.replace or str.lower.

In [200]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank"],
    "Age": [24, 32, 28, 40, 22, 30],
    "City": ["Delhi", "Mumbai", "Pune", "Chennai", "Delhi", "Mumbai"],
    "Score": [90, 82, 88, 75, 95, 84]
}

df = pd.DataFrame(data)
df[df["Age"] > 25]

      Name  Age     City  Score
1      Bob   32   Mumbai     82
2  Charlie   28     Pune     88
3    David   40  Chennai     75
5    Frank   30   Mumbai     84

In [203]:
df[df["City"].isin(["Delhi", "Mumbai"])]

    Name  Age    City  Score
0  Alice   24   Delhi     90
1    Bob   32  Mumbai     82
4   Emma   22   Delhi     95
5  Frank   30  Mumbai     84

In [204]:
df.query("Score >= 85 and Age < 35")

      Name  Age   City  Score
0    Alice   24  Delhi     90
2  Charlie   28   Pune     88
4     Emma   22  Delhi     95

In [214]:
s = df
s["City"] = s["City"].str.replace("Delhi", "New Delhi")
s["City"] = s["City"].str.lower()
s

      Name  Age                           City  Score
0    Alice   24  new new new new new new delhi     90
1      Bob   32                         mumbai     82
2  Charlie   28                           pune     88
3    David   40                        chennai     75
4     Emma   22  new new new new new new delhi     95
5    Frank   30                         mumbai     84

## Sorting Data
- Use `sort_values(by='col')` to sort by column values.
- Use `ascending=False` for descending order.
- Sort by multiple columns by passing a list.
- `sort_index()` sorts by row or column index.

In [2]:
import pandas as pd
data = {
    "Product": ["Pen", "Notebook", "Pencil", "Marker", "Eraser", "Sharpener"],
    "Price": [10, 50, 5, 30, 8, 12],
    "Stock": [100, 60, 200, 80, 150, 120],
    "Rating": [4.5, 4.7, 4.2, 4.8, 4.3, 4.4]
}

df = pd.DataFrame(data)
df

     Product  Price  Stock  Rating
0        Pen     10    100     4.5
1   Notebook     50     60     4.7
2     Pencil      5    200     4.2
3     Marker     30     80     4.8
4     Eraser      8    150     4.3
5  Sharpener     12    120     4.4

In [6]:
print(df.sort_values(by = "Price"))
print(df.sort_values(by = "Price", ascending = False))
print(df.sort_values(by = ["Price", "Rating"]))
print(df.sort_values(by = ["Price", "Stock"], ascending = [False, True]))

     Product  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1   Notebook     50     60     4.7
     Product  Price  Stock  Rating
1   Notebook     50     60     4.7
3     Marker     30     80     4.8
5  Sharpener     12    120     4.4
0        Pen     10    100     4.5
4     Eraser      8    150     4.3
2     Pencil      5    200     4.2
     Product  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1   Notebook     50     60     4.7
     Product  Price  Stock  Rating
1   Notebook     50     60     4.7
3     Marker     30     80     4.8
5  Sharpener     12    120     4.4
0        Pen     10    100     4.5
4     Eraser      8    150     4.3
2     Pencil      5    200     4.2

## Descriptive Statistics
- `mean()`,` median()`, `mode()` for central tendency.
- `std()` for standard deviation.
- `describe()` for a summary of stats (count, mean, std, min, quartiles, max).

In [9]:
df.mean(numeric_only=True)

Price      19.166667
Stock     118.333333
Rating      4.483333
dtype: float64

In [10]:
df.median(numeric_only=True)

Price      11.00
Stock     110.00
Rating      4.45
dtype: float64

In [11]:
df.mode()

     Product  Price  Stock  Rating
0     Eraser      5     60     4.2
1     Marker      8     80     4.3
2   Notebook     10    100     4.4
3        Pen     12    120     4.5
4     Pencil     30    150     4.7
5  Sharpener     50    200     4.8

In [12]:
df.std(numeric_only = True)

Price     17.486185
Stock     50.760877
Rating     0.231661
dtype: float64

In [14]:
df.describe()

           Price       Stock    Rating
count   6.000000    6.000000  6.000000
mean   19.166667  118.333333  4.483333
std    17.486185   50.760877  0.231661
min     5.000000   60.000000  4.200000
25%     8.500000   85.000000  4.325000
50%    11.000000  110.000000  4.450000
75%    25.500000  142.500000  4.650000
max    50.000000  200.000000  4.800000

## Counting Values
- `value_counts()` shows the frequency of unique values in a Series.
- Use `normalize=True` to see percentages instead of counts.

In [15]:
print(df.value_counts("Product"))

Product
Eraser       1
Marker       1
Notebook     1
Pen          1
Pencil       1
Sharpener    1
Name: count, dtype: int64

In [16]:
df.value_counts("Product", normalize=True)

Product
Eraser       0.166667
Marker       0.166667
Notebook     0.166667
Pen          0.166667
Pencil       0.166667
Sharpener    0.166667
Name: proportion, dtype: float64

## Correlation & Covariance
- `corr()` computes correlation between numeric columns.
- `cov()` computes covariance.
- Correlation values range from -1 (negative) to +1 (positive).

In [18]:
df.corr(numeric_only = True)

           Price     Stock    Rating
Price   1.000000 -0.804028  0.820402
Stock  -0.804028  1.000000 -0.921257
Rating  0.820402 -0.921257  1.000000

In [19]:
df.cov(numeric_only = True)

             Price        Stock     Rating
Price   305.766667  -713.666667   3.323333
Stock  -713.666667  2576.666667 -10.833333
Rating    3.323333   -10.833333   0.053667

In [20]:
print(df["Price"].corr(df["Stock"]))

-0.8040280933316356

## Mini Practice
- Build a DataFrame with columns: Name, Age, Score, Height.
- Sort the data by Score (descending).
- Get mean, median, mode, and std of numeric columns.
- Use value_counts on Name or any categorical column.
- Compute corr() and cov() for all numeric columns.

In [4]:
import pandas as pd
data = {
    "Name": ["Liam", "Sophia", "Ethan", "Olivia", "Noah"],
    "Age": [27, 34, 29, 31, 26],
    "Score": [80, 95, 88, 76, 90],
    "Height": [172, 165, 180, 158, 175]
}

df = pd.DataFrame(data)
print(df.sort_values(by = "Score" , ascending= False))
print(df.mean(numeric_only=True))
print(df.median(numeric_only=True))
print(df.mode())
print(df.std(numeric_only=True))
print(df.value_counts("Name"))
print(df.corr(numeric_only=True))
print(df.cov(numeric_only=True))

     Name  Age  Score  Height
1  Sophia   34     95     165
4    Noah   26     90     175
2   Ethan   29     88     180
0    Liam   27     80     172
3  Olivia   31     76     158
Age        29.4
Score      85.8
Height    170.0
dtype: float64
Age        29.0
Score      88.0
Height    172.0
dtype: float64
     Name  Age  Score  Height
0   Ethan   26     76     158
1    Liam   27     80     165
2    Noah   29     88     172
3  Olivia   31     90     175
4  Sophia   34     95     180
Age       3.209361
Score     7.694154
Height    8.631338
dtype: float64

          Age  Score  Height
Age     10.30   6.35  -17.00
Score    6.35  59.20   25.75
Height -17.00  25.75   74.50

## Concept of Split–Apply–Combine
- Split the data into groups based on some criteria.
- Apply a function (e.g., sum, mean) to each group.
- Combine the results into a new DataFrame or Series.
- This is the core idea behind `groupby`.

In [16]:
import pandas as pd

data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
print("\nAverage salary by Department:")
print(df.groupby("Department")["Salary"].mean())
print("\nNumber of employees by Department:")
print(df.groupby("Department")["Employee"].count())
print("\nSalary stats (mean, max, min) by Department:")
print(df.groupby("Department")["Salary"].agg(["mean", "max", "min"]))

Average salary by Department:
Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

Number of employees by Department:
Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

Salary stats (mean, max, min) by Department:
                    mean    max    min
Department
Finance     61000.000000  65000  58000
HR          51000.000000  52000  50000
IT          72333.333333  75000  70000

## Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [20]:
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
df.groupby("Department").agg({
    "Salary": ["max", "min"],
    "Age" : ["mean", "max"]
})

           Salary               Age
              max    min       mean max
Department
Finance     65000  58000  29.333333  35
HR          52000  50000  28.500000  29
IT          75000  70000  31.000000  32

## Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups

In [23]:
df
print("\nPivot table: Average Salary by Department")
print(df.pivot_table(values = "Salary", index = "Department", aggfunc = "mean"))
print("\nPivot table: Average Salary & Age by Department")
print(df.pivot_table(values = ["Salary" , "Age"], index = "Department", aggfunc = "mean"))

# Crosstab: number of employees by Department and Age group
# Let's create an AgeGroup column
df["AgeGroup"] = pd.cut(df["Age"], bins=[25, 30, 35, 40], labels=["25-30", "31-35", "36-40"])
crosstab_result = pd.crosstab(df["Department"], df["AgeGroup"])
print("\nCrosstab: Employees by Department and Age Group")
print(crosstab_result)

Pivot table: Average Salary by Department
                  Salary
Department
Finance     61000.000000
HR          51000.000000
IT          72333.333333

Pivot table: Average Salary & Age by Department
                  Age        Salary
Department
Finance     29.333333  61000.000000
HR          28.500000  51000.000000
IT          31.000000  72333.333333

## Mini Practice
- Create a DataFrame with columns: Department, Employee, Salary, Age, City.
- Group by Department to get average Salary and max Age.
- Apply multiple aggregations using agg().
- Create a pivot_table to see mean Salary by Department and City.
- Build a crosstab for Department vs City.

In [27]:
data = {
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance", "IT", "HR"],
    "Employee": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank", "George", "Hannah"],
    "Salary": [50000, 65000, 60000, 70000, 52000, 58000, 72000, 51000],
    "Age": [28, 35, 30, 40, 26, 32, 38, 27],
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai", "Mumbai", "Delhi", "Mumbai", "Delhi"]
}

df = pd.DataFrame(data)
df.groupby("Department").agg({
    "Salary": "mean",
    "Age": "max"
    })
df.pivot_table(values = "Salary", index =["Department", "City"], aggfunc= "mean")

                     Salary
Department City
Finance    Delhi    59000.0
HR         Delhi    50500.0
           Mumbai   52000.0
IT         Chennai  70000.0
           Mumbai   68500.0

## Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), axis=1 for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [7]:
import pandas as pd
# Dataset 1: Product details
df1 = pd.DataFrame({
    "ProductID": [101, 102, 103],
    "ProductName": ["Pen", "Notebook", "Marker"],
    "Price": [10, 50, 30]
})

# Dataset 2: More products (same columns as df1)
df2 = pd.DataFrame({
    "ProductID": [104, 105],
    "ProductName": ["Pencil", "Eraser"],
    "Price": [5, 8]
})

# Dataset 3: Additional info (different columns)
df3 = pd.DataFrame({
    "Stock": [100, 60, 80],
    "Rating": [4.5, 4.7, 4.8]
})

print("Original DataFrames:")
print("\nDF1:\n", df1)
print("\nDF2:\n", df2)
print("\nDF3:\n", df3)

pd.concat([df1, df2], axis = 0, ignore_index=True)

Original DataFrames:

DF1:
    ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30

DF2:
    ProductID ProductName  Price
0        104      Pencil      5
1        105      Eraser      8

DF3:
    Stock  Rating
0    100     4.5
1     60     4.7
2     80     4.8

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
0        104      Pencil      5
1        105      Eraser      8

In [8]:
pd.concat([df1, df3], axis = 1)

   ProductID ProductName  Price  Stock  Rating
0        101         Pen     10    100     4.5
1        102    Notebook     50     60     4.7
2        103      Marker     30     80     4.8

##  Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [21]:
products = pd.concat([df1, df2], axis=0, ignore_index=True)
print("\n product data")
print(products)

sales = pd.DataFrame({
    "ProductID": [101, 102, 104, 106],  # 106 doesn't exist in products
    "UnitsSold": [500, 200, 150, 50]
})
print("\n sales data")
print(sales)

print("\nInner Join (only matches):")
print(pd.merge(products, sales, on = "ProductID", how = "inner"))    # inner -> only the common values of product ID will be shown in the table
print("\nOuter Join (all data):")
print(pd.merge(products, sales, on = "ProductID", how = "outer") )   # outer -> all teh values of product ID will be shown in the table
print("\nLeft Join (all products):")
print(pd.merge(products, sales, on = "ProductID", how = "left") )
print("\nRight Join (all sales):")
print(pd.merge(products, sales, on = "ProductID", how = "right") )

 product data
   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      8

 sales data
   ProductID  UnitsSold
0        101        500
1        102        200
2        104        150
3        106         50

Inner Join (only matches):
   ProductID ProductName  Price  UnitsSold
0        101         Pen     10        500
1        102    Notebook     50        200
2        104      Pencil      5        150

Outer Join (all data):
   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0      500.0
1        102    Notebook   50.0      200.0
2        103      Marker   30.0        NaN
3        104      Pencil    5.0      150.0
4        105      Eraser    8.0        NaN
5        106         NaN    NaN       50.0

Left Join (all products):
   ProductID ProductName  Price  UnitsSold
0        101         Pen     10      500.0
1        102    Notebook     50      200.0
2        103      Marker     30        NaN
3        104      Pencil      5      150.0
4        105      Eraser      8        NaN

Right Join (all sales):
   ProductID ProductName  Price  UnitsSold
0        101         Pen   10.0        500
1        102    Notebook   50.0        200
2        104      Pencil    5.0        150
3        106         NaN    NaN         50

## Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [32]:
products = pd.concat([df1, df2], ignore_index=True)
print("\n product data")
print(products)

stock = pd.DataFrame({
    "Stock": [100, 60, 80, 120, 150],
}, index=[101, 102, 103, 104, 105])      # ProductID as index
print("\n stock data")
print(stock)

p_data = products.set_index("ProductID")
print(p_data)
print("\n Joined data")
p_data.join(stock, on = "ProductID", how="outer")

 product data
   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      8

 stock data
     Stock
101    100
102     60
103     80
104    120
105    150
          ProductName  Price
ProductID
101               Pen     10
102          Notebook     50
103            Marker     30
104            Pencil      5
105            Eraser      8

 Joined data

          ProductName  Price  Stock
ProductID
101               Pen     10    100
102          Notebook     50     60
103            Marker     30     80
104            Pencil      5    120
105            Eraser      8    150

In [33]:
# Sales data
sales = pd.DataFrame({
    "ProductID": [201, 202, 203, 204],
    "UnitsSold": [500, 300, 400, 250]
})

# Revenue data (missing ProductID 204, extra 205)
revenue = pd.DataFrame({
    "ProductID": [201, 202, 203, 205],
    "Revenue": [7500, 4500, 6800, 1200]
})

print("Sales Data:")
print(sales)
print("\nRevenue Data:")
print(revenue)

# Merge sales and revenue to see performance
merged_perf = pd.merge(sales, revenue, on="ProductID", how="outer")
print("\nMerged Sales & Revenue (outer join):")
print(merged_perf)

Sales Data:
   ProductID  UnitsSold
0        201        500
1        202        300
2        203        400
3        204        250

Revenue Data:
   ProductID  Revenue
0        201     7500
1        202     4500
2        203     6800
3        205     1200

Merged Sales & Revenue (outer join):
   ProductID  UnitsSold  Revenue
0        201      500.0   7500.0
1        202      300.0   4500.0
2        203      400.0   6800.0
3        204      250.0      NaN
4        205        NaN   1200.0

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [41]:
products = pd.DataFrame({
    "ProductID": [101, 102, 103, 104],
    "ProductName": ["Pen", "Notebook", "Pencil", "Eraser"]
})

sales = pd.DataFrame({
    "ProductID": [101, 102, 103, 105],
    "UnitsSold": [200, 150, 300, 50]
})

revenue = pd.DataFrame({
    "ProductID": [101, 102, 104, 105],
    "Revenue": [1000, 2500, 800, 200]
})

print("Products DataFrame:")
print(products)
print("\nSales DataFrame:")
print(sales)
print("\nRevenue DataFrame:")
print(revenue)

print(pd.concat([products, sales], axis = 0, ignore_index=True))
print(pd.concat([products, sales], axis = 1))

pd.merge(sales , revenue, on = "ProductID", how = "inner")

pd.merge(products, sales, on = "ProductID", how = "outer")

Products DataFrame:
   ProductID ProductName
0        101         Pen
1        102    Notebook
2        103      Pencil
3        104      Eraser

Sales DataFrame:
   ProductID  UnitsSold
0        101        200
1        102        150
2        103        300
3        105         50

Revenue DataFrame:
   ProductID  Revenue
0        101     1000
1        102     2500
2        104      800
3        105      200
   ProductID ProductName  UnitsSold
0        101         Pen        NaN
1        102    Notebook        NaN
2        103      Pencil        NaN
3        104      Eraser        NaN
4        101         NaN      200.0
5        102         NaN      150.0
6        103         NaN      300.0
7        105         NaN       50.0
   ProductID ProductName  ProductID  UnitsSold
0        101         Pen        101        200
1        102    Notebook        102        150
2        103      Pencil        103        300
3        104      Eraser        105         50

   ProductID ProductName  UnitsSold
0        101         Pen      200.0
1        102    Notebook      150.0
2        103      Pencil      300.0
3        104      Eraser        NaN
4        105         NaN       50.0

## Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [59]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Math": [88, 75, 92, 60, 85],
    "Science": [90, 80, 78, 70, 95]
}

df = pd.DataFrame(data)
df["total"] = df[["Math", "Science"]].apply(lambda r: r.sum(), axis = 1)

col_mean = df[["Math", "Science"]].apply(lambda c: c.mean(), axis = 0)
print(col_mean)

def get_grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    elif score >= 60:
        return "D"
    else:
        return "F"

df["Grade"] = df["Math"].apply(get_grade)
print(df)

df["Name"] = df["Name"].map(str.lower)
print(df)

df["Math"] = df["Math"].map(lambda x: x + 5)
print(df)

Math       80.0
Science    82.6
dtype: float64
      Name  Math  Science  total Grade
0    Alice    88       90    178     B
1      Bob    75       80    155     C
2  Charlie    92       78    170     A
3    David    60       70    130     D
4     Emma    85       95    180     B
      Name  Math  Science  total Grade
0    alice    88       90    178     B
1      bob    75       80    155     C
2  charlie    92       78    170     A
3    david    60       70    130     D
4     emma    85       95    180     B
      Name  Math  Science  total Grade
0    alice    93       90    178     B
1      bob    80       80    155     C
2  charlie    97       78    170     A
3    david    65       70    130     D
4     emma    90       95    180     B