<a href="https://colab.research.google.com/github/sh1vam31/Complete_DataScience/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**

## 1 What is Pandas and Why Use It?
Pandas is a powerful Python library for data analysis and manipulation.

Key points:

Provides two main data structures: Series (1D) and DataFrame (2D).
Makes working with tabular data easy and fast.
Ideal for cleaning, transforming, and analyzing datasets.
Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

### Import the pandas

In [2]:
import numpy as np
import pandas as pd

## 2 Understanding Series & DataFrame



*   Series: One-dimensional labeled array, like a column in Excel.
*   DataFrame: Two-dimensional table, similar to an Excel sheet or SQL table.

## Creating a Series from Python Lists or Dictionaries

In [9]:
a = [12, 34, 45, 74, 66]
s = pd.Series(a, name = "Marks")
s

d = {"vashu": 99, "shivam": 88,}
s2 = pd.Series(d, name = "marks")
s2

vashu     99
shivam    88
Name: marks, dtype: int64

## Creating a DataFrame

In [10]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [90, 85, 78, 92],
    "Subject": ["Math", "Science", "History", "English"]
}

pd.DataFrame(a)

      Name  Marks  Subject
0    Alice     90     Math
1      Bob     85  Science
2  Charlie     78  History
3    David     92  English

## Creating DataFrame from NumPy Arrays

In [15]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

df = pd.DataFrame(a, columns = ["A", "B", "C"])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

## 1 Inspecting Data
Quick ways to understand your dataset:

- head(n) → first n rows (default 5)
- tail(n) → last n rows
- info() → columns, non-null counts, and dtypes
- shape → (rows, columns)
- dtypes → data type of each column

In [9]:
import pandas as pd

a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
b
print()
print(b.head())
print()
print(b.head(3))
print()
print(b.tail())
print()
print(b.tail(2))
print()
print(b.shape)
print()
print(b.info())
print()
print(b.dtypes)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

    Name  Age  Score
3  David   40     85
4   Emma   22     95

(5, 3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None

Name     object
Age       int64
Score     int64
dtype: object

## 2 Selecting Columns & Rows
Ways to access parts of a DataFrame:

- Single column → `df['col']`
- Multiple columns → `df[['col1','col2']]`
- Label-based selection → `df.loc[row_label, col_label]`
- Integer-index selection → `df.iloc[row_idx, col_idx]` Tip: : means "all rows/columns" in that dimension.

In [26]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
print(b)
print()
print(b["Name"])
print()
print(b[["Name", "Age"]])     # whenever we use the fancy indexing we have to use the 2 square brackats
print()
print(b.loc[1])
print()
print(b.loc[[2, 3]])
print()
print(b.loc[4,"Score"])
print()
print(b.loc[1:4, ["Name", "Age"]])
print()
print(b.iloc[2, 2])

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

0      Alice
1        Bob
2    Charlie
3      David
4       Emma
Name: Name, dtype: object

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   22

Name     Bob
Age       30
Score     92
Name: 1, dtype: object

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

95

      Name  Age
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   22

79

## 3 Index & Columns Overview
- `df.index` → row labels
- `df.columns` → column names
- `df.values` → underlying NumPy array

In [32]:
print(b)
print()
print(b.index)
print()
print(b.columns)
print()
print(b.values)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

RangeIndex(start=0, stop=5, step=1)

Index(['Name', 'Age', 'Score'], dtype='object')

[['Alice' 25 88]
 ['Bob' 30 92]
 ['Charlie' 35 79]
 ['David' 40 85]
 ['Emma' 22 95]]

## 4 Renaming Columns & Setting an Index
- Rename columns → `df.rename(columns={'old':'new'}, inplace=False)`
- Set a column as `index → df.set_index('column_name', inplace=False)`
- Reset index → `df.reset_index(inplace=False)` If you don't use `inplace=True`, remember to assign the result back to a variable.

In [48]:
print(b)
print()
c = b.rename(columns = {"Score": "marks"}, inplace = False)
print(c)
print("\nThe Original dataframe")
print(b)
print()
c = b.set_index("Name")
print(c)
print()
b.reset_index(inplace = False)
print(b)

   index     Name  Age  Score
0      0    Alice   25     88
1      1      Bob   30     92
2      2  Charlie   35     79
3      3    David   40     85
4      4     Emma   22     95

   index     Name  Age  marks
0      0    Alice   25     88
1      1      Bob   30     92
2      2  Charlie   35     79
3      3    David   40     85
4      4     Emma   22     95

The Original dataframe
   index     Name  Age  Score
0      0    Alice   25     88
1      1      Bob   30     92
2      2  Charlie   35     79
3      3    David   40     85
4      4     Emma   22     95

         index  Age  Score
Name
Alice        0   25     88
Bob          1   30     92
Charlie      2   35     79
David        3   40     85
Emma         4   22     95

   index     Name  Age  Score
0      0    Alice   25     88
1      1      Bob   30     92
2      2  Charlie   35     79
3      3    David   40     85
4      4     Emma   22     95

## Mini Practice
- Create a DataFrame with at least 5 rows and 4 columns (mix of numeric + text).
- Show the first 3 rows, last 2 rows, and the info.
- Select a sub-DataFrame with only 2 columns.
- Rename one column and set any column as index, then reset it back.
- Print df.shape, df.dtypes, and df.columns.

In [66]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Chennai"],
    "Score": [85, 91, 78, 88, 95]
}

df = pd.DataFrame(data)
print("\nFirst Three Rows")
print(df.head(3))
print("\nLast Two Rows")
print(df.tail(2))
print("\nInfo")
print(df.info())
print("\n 2 columns")
print(df[["Name", "Age"]])
print("\n Rename")
c = df.rename(columns = {"Score" : "Marks"})
print(c)
print("\n Set Index")
s = df.set_index("Name")
print(s)
print("\n Shape")
print(df.shape)
print("\n Dtypes")
print(df.dtypes)
print("\n Columns")
print(df.columns)

First Three Rows
      Name  Age    City  Score
0    Alice   25   Delhi     85
1      Bob   30  Mumbai     91
2  Charlie   35    Pune     78

Last Two Rows
    Name  Age       City  Score
3  David   40  Bangalore     88
4   Emma   22    Chennai     95

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Score   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None

 2 columns
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   22

 Rename
      Name  Age       City  Marks
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     91
2  Charlie   35       Pune     78
3    David   40  Bangalore     88
4     Emma   22    Chennai     95

 Set Index
         Age       City  Score
Name
Alice     25      Delhi     85
Bob       30     Mumbai     91
Charlie   35       Pune     78
David     40  Bangalore     88
Emma      22    Chennai     95

 Shape
(5, 4)

 Dtypes
Name     object
Age       int64
City     object
Score     int64
dtype: object

 Columns
Index(['Name', 'Age', 'City', 'Score'], dtype='object')